import random

ASSET_DATA = {
    "stocks": [
        {"name": "Reliance Industries", "ticker": "RELIANCE.NS", "market_cap": "Large", "sector": "Energy", "predicted_return": 0.15, "volatility": "Low", "price": 2900},
        {"name": "TCS", "ticker": "TCS.NS", "market_cap": "Large", "sector": "IT", "predicted_return": 0.13, "volatility": "Low", "price": 3800},
        {"name": "HDFC Bank", "ticker": "HDFCBANK.NS", "market_cap": "Large", "sector": "Financials", "predicted_return": 0.18, "volatility": "Low", "price": 1600}, # Increased return for testing
        {"name": "Infosys", "ticker": "INFY.NS", "market_cap": "Large", "sector": "IT", "predicted_return": 0.14, "volatility": "Low", "price": 1700},
        {"name": "Bharti Airtel", "ticker": "BHARTIARTL.NS", "market_cap": "Large", "sector": "Telecom", "predicted_return": 0.11, "volatility": "Low", "price": 1200},
        {"name": "ICICI Bank", "ticker": "ICICIBANK.NS", "market_cap": "Large", "sector": "Financials", "predicted_return": 0.17, "volatility": "Low", "price": 1100}, # Increased return
        {"name": "Larsen & Toubro", "ticker": "LT.NS", "market_cap": "Large", "sector": "Capital Goods", "predicted_return": 0.14, "volatility": "Low", "price": 3700},
        {"name": "Bajaj Finance", "ticker": "BAJFINANCE.NS", "market_cap": "Mid", "sector": "Financials", "predicted_return": 0.20, "volatility": "Medium", "price": 7200}, # Increased return
        {"name": "Titan Company", "ticker": "TITAN.NS", "market_cap": "Mid", "sector": "Consumer Discretionary", "predicted_return": 0.16, "volatility": "Medium", "price": 3500},
        {"name": "Dixon Technologies", "ticker": "DIXON.NS", "market_cap": "Mid", "sector": "Electronics", "predicted_return": 0.20, "volatility": "High", "price": 11000},
        {"name": "Godrej Properties", "ticker": "GODREJPROP.NS", "market_cap": "Mid", "sector": "Real Estate", "predicted_return": 0.17, "volatility": "Medium", "price": 2700},
        {"name": "Mindtree", "ticker": "MINDTREE.NS", "market_cap": "Mid", "sector": "IT", "predicted_return": 0.19, "volatility": "Medium", "price": 5000},
        {"name": "CDSL", "ticker": "CDSL.NS", "market_cap": "Small", "sector": "Financials", "predicted_return": 0.25, "volatility": "High", "price": 2100}, # Increased return
        {"name": "Affle India", "ticker": "AFFLE.NS", "market_cap": "Small", "sector": "IT", "predicted_return": 0.22, "volatility": "High", "price": 1200},
        {"name": "Tanla Platforms", "ticker": "TANLA.NS", "market_cap": "Small", "sector": "IT", "predicted_return": 0.23, "volatility": "High", "price": 1000},
        {"name": "Happiest Minds", "ticker": "HAPPSTMNDS.NS", "market_cap": "Small", "sector": "IT", "predicted_return": 0.24, "volatility": "High", "price": 900},
        {"name": "Fineotex Chemical", "ticker": "FCL.NS", "market_cap": "Small", "sector": "Chemicals", "predicted_return": 0.26, "volatility": "High", "price": 400},
        {"name": "Asian Paints", "ticker": "ASIANPAINT.NS", "market_cap": "Large", "sector": "Chemicals", "predicted_return": 0.10, "volatility": "Low", "price": 2900},
        {"name": "Bajaj Auto", "ticker": "BAJAJ-AUTO.NS", "market_cap": "Large", "sector": "Automobile", "predicted_return": 0.12, "volatility": "Low", "price": 9500},
        {"name": "Bajaj Finserv", "ticker": "BAJAJFINSV.NS", "market_cap": "Large", "sector": "Financials", "predicted_return": 0.19, "volatility": "Medium", "price": 1600}, # Increased return
        {"name": "Britannia Industries", "ticker": "BRITANNIA.NS", "market_cap": "Large", "sector": "FMCG", "predicted_return": 0.10, "volatility": "Low", "price": 5000},
        {"name": "Cipla", "ticker": "CIPLA.NS", "market_cap": "Large", "sector": "Pharma", "predicted_return": 0.11, "volatility": "Low", "price": 1500},
        {"name": "Coal India", "ticker": "COALINDIA.NS", "market_cap": "Large", "sector": "Mining", "predicted_return": 0.08, "volatility": "Medium", "price": 450},
        {"name": "Divi's Lab", "ticker": "DIVISLAB.NS", "market_cap": "Large", "sector": "Pharma", "predicted_return": 0.15, "volatility": "Medium", "price": 3800},
        {"name": "Dr Reddy's Laboratories", "ticker": "DRL.NS", "market_cap": "Large", "sector": "Pharma", "predicted_return": 0.13, "volatility": "Low", "price": 6000},
        {"name": "Eicher Motors", "ticker": "EICHERMOT.NS", "market_cap": "Large", "sector": "Automobile", "predicted_return": 0.16, "volatility": "Medium", "price": 4300},
        {"name": "Grasim Industries", "ticker": "GRASIM.NS", "market_cap": "Large", "sector": "Cement", "predicted_return": 0.10, "volatility": "Low", "price": 2500},
        {"name": "HCL Technologies", "ticker": "HCLTECH.NS", "market_cap": "Large", "sector": "IT", "predicted_return": 0.12, "volatility": "Low", "price": 1400},
        {"name": "Hero MotoCorp", "ticker": "HEROMOTOCO.NS", "market_cap": "Large", "sector": "Automobile", "predicted_return": 0.09, "volatility": "Low", "price": 4800},
        {"name": "Hindalco Industries", "ticker": "HINDALCO.NS", "market_cap": "Large", "sector": "Metals", "predicted_return": 0.14, "volatility": "Medium", "price": 680},
        {"name": "Hindustan Unilever", "ticker": "HINDUNILVR.NS", "market_cap": "Large", "sector": "FMCG", "predicted_return": 0.10, "volatility": "Low", "price": 2500},
        {"name": "IndusInd Bank", "ticker": "INDUSINDBK.NS", "market_cap": "Large", "sector": "Financials", "predicted_return": 0.16, "volatility": "Medium", "price": 1500}, # Increased return
        {"name": "Kotak Mahindra Bank", "ticker": "KOTAKBANK.NS", "market_cap": "Large", "sector": "Financials", "predicted_return": 0.17, "volatility": "Low", "price": 1700}, # Increased return
        {"name": "Mahindra & Mahindra", "ticker": "M&M.NS", "market_cap": "Large", "sector": "Automobile", "predicted_return": 0.13, "volatility": "Medium", "price": 2400},
        {"name": "Maruti Suzuki India", "ticker": "MARUTI.NS", "market_cap": "Large", "sector": "Automobile", "predicted_return": 0.15, "volatility": "Low", "price": 12500},
        {"name": "Nestle India", "ticker": "NESTLEIND.NS", "market_cap": "Large", "sector": "FMCG", "predicted_return": 0.10, "volatility": "Low", "price": 25000},
        {"name": "NTPC", "ticker": "NTPC.NS", "market_cap": "Large", "sector": "Power", "predicted_return": 0.07, "volatility": "Low", "price": 350},
        {"name": "Oil & Natural Gas Corporation", "ticker": "ONGC.NS", "market_cap": "Large", "sector": "Energy", "predicted_return": 0.09, "volatility": "Medium", "price": 280},
        {"name": "Power Grid Corporation of India", "ticker": "POWERGRID.NS", "market_cap": "Large", "sector": "Power", "predicted_return": 0.08, "volatility": "Low", "price": 300},
        {"name": "SBI Life Insurance Company", "ticker": "SBILIFE.NS", "market_cap": "Large", "sector": "Financials", "predicted_return": 0.15, "volatility": "Low", "price": 1400}, # Increased return
        {"name": "Shree Cement", "ticker": "SHREECEM.NS", "market_cap": "Large", "sector": "Cement", "predicted_return": 0.12, "volatility": "Medium", "price": 27000},
        {"name": "Sun Pharmaceutical Industries", "ticker": "SUNPHARMA.NS", "market_cap": "Large", "sector": "Pharma", "predicted_return": 0.13, "volatility": "Low", "price": 1600},
        {"name": "Tata Consumer Products", "ticker": "TATACONSUM.NS", "market_cap": "Large", "sector": "FMCG", "predicted_return": 0.10, "volatility": "Low", "price": 1100},
        {"name": "Tata Motors", "ticker": "TATAMOTORS.NS", "market_cap": "Large", "sector": "Automobile", "predicted_return": 0.15, "volatility": "Medium", "price": 1000},
        {"name": "Tata Steel", "ticker": "TATASTEEL.NS", "market_cap": "Large", "sector": "Metals", "predicted_return": 0.14, "volatility": "High", "price": 180},
        {"name": "Tech Mahindra", "ticker": "TECHM.NS", "market_cap": "Large", "sector": "IT", "predicted_return": 0.12, "volatility": "Low", "price": 1300},
        {"name": "Ultratech Cement", "ticker": "ULTRACEMCO.NS", "market_cap": "Large", "sector": "Cement", "predicted_return": 0.11, "volatility": "Low", "price": 10000},
        {"name": "UPL", "ticker": "UPL.NS", "market_cap": "Large", "sector": "Chemicals", "predicted_return": 0.09, "volatility": "Medium", "price": 550},
        {"name": "Wipro", "ticker": "WIPRO.NS", "market_cap": "Large", "sector": "IT", "predicted_return": 0.10, "volatility": "Low", "price": 500},
        {"name": "Adani Enterprises", "ticker": "ADANIENT.NS", "market_cap": "Large", "sector": "Diversified", "predicted_return": 0.18, "volatility": "High", "price": 3300},
        {"name": "Adani Ports and Special Economic Zone", "ticker": "ADANIPORTS.NS", "market_cap": "Large", "sector": "Logistics", "predicted_return": 0.16, "volatility": "Medium", "price": 1400},
        {"name": "Apollo Hospitals Enterprise", "ticker": "APOLLOHOSP.NS", "market_cap": "Large", "sector": "Healthcare", "predicted_return": 0.15, "volatility": "Medium", "price": 6000},
        {"name": "Axis Bank", "ticker": "AXISBANK.NS", "market_cap": "Large", "sector": "Financials", "predicted_return": 0.165, "volatility": "Low", "price": 1200}, # Increased return
        {"name": "Bharat Petroleum Corporation", "ticker": "BPCL.NS", "market_cap": "Large", "sector": "Oil & Gas", "predicted_return": 0.08, "volatility": "Low", "price": 600},
        {"name": "Adani Green Energy", "ticker": "ADANIGREEN.NS", "market_cap": "Large", "sector": "Renewable Energy", "predicted_return": 0.20, "volatility": "High", "price": 1800},
        {"name": "Adani Transmission", "ticker": "ADANITRANS.NS", "market_cap": "Large", "sector": "Power Transmission", "predicted_return": 0.18, "volatility": "High", "price": 2000},
        {"name": "Ambuja Cements", "ticker": "AMBUJACEM.NS", "market_cap": "Large", "sector": "Cement", "predicted_return": 0.10, "volatility": "Low", "price": 600},
        {"name": "AU Small Finance Bank", "ticker": "AUBANK.NS", "market_cap": "Mid", "sector": "Financials", "predicted_return": 0.19, "volatility": "Medium", "price": 700}, # Increased return
        {"name": "Bandhan Bank", "ticker": "BANDHANBNK.NS", "market_cap": "Mid", "sector": "Financials", "predicted_return": 0.17, "volatility": "Medium", "price": 220}, # Increased return
        {"name": "Berger Paints India", "ticker": "BERGEPAINT.NS", "market_cap": "Large", "sector": "Chemicals", "predicted_return": 0.11, "volatility": "Low", "price": 650},
        {"name": "Bosch", "ticker": "BOSCHLTD.NS", "market_cap": "Large", "sector": "Automobile Ancillaries", "predicted_return": 0.10, "volatility": "Low", "price": 22000},
        {"name": "Bharat Forge", "ticker": "BHARATFORG.NS", "market_cap": "Mid", "sector": "Industrial Goods", "predicted_return": 0.15, "volatility": "Medium", "price": 1300},
        {"name": "Biocon", "ticker": "BIOCON.NS", "market_cap": "Mid", "sector": "Biotechnology", "predicted_return": 0.13, "volatility": "Medium", "price": 280},
        {"name": "Chola Investment", "ticker": "CHOLAFIN.NS", "market_cap": "Large", "sector": "Financials", "predicted_return": 0.20, "volatility": "Medium", "price": 1300}, # Increased return
        {"name": "Dabur India", "ticker": "DABUR.NS", "market_cap": "Large", "sector": "FMCG", "predicted_return": 0.10, "volatility": "Low", "price": 550},
        {"name": "DLF", "ticker": "DLF.NS", "market_cap": "Large", "sector": "Real Estate", "predicted_return": 0.14, "volatility": "Medium", "price": 900},
        {"name": "Godrej Consumer Products", "ticker": "GODREJCP.NS", "market_cap": "Large", "sector": "FMCG", "predicted_return": 0.11, "volatility": "Low", "price": 1200},
        {"name": "Hindware Home Innovation", "ticker": "HINDWARE.NS", "market_cap": "Small", "sector": "Consumer Durables", "predicted_return": 0.19, "volatility": "High", "price": 450},
        {"name": "Indiamart Intermesh", "ticker": "INDIAMART.NS", "market_cap": "Mid", "sector": "E-commerce", "predicted_return": 0.22, "volatility": "High", "price": 2700},
        {"name": "Indian Railway Catering & Tourism Corp Ltd", "ticker": "IRCTC.NS", "market_cap": "Mid", "sector": "Tourism", "predicted_return": 0.17, "volatility": "Medium", "price": 1100},
        {"name": "IPCA Laboratories", "ticker": "IPCALAB.NS", "market_cap": "Large", "sector": "Pharma", "predicted_return": 0.12, "volatility": "Low", "price": 1100},
        {"name": "Jubilant FoodWorks", "ticker": "JUBLFOOD.NS", "market_cap": "Large", "sector": "Restaurants", "predicted_return": 0.16, "volatility": "Medium", "price": 550},
        {"name": "LIC Housing Finance", "ticker": "LICHSGFIN.NS", "market_cap": "Mid", "sector": "Financials", "predicted_return": 0.15, "volatility": "Low", "price": 700}, # Increased return
        {"name": "Laurus Labs", "ticker": "LAURUSLABS.NS", "market_cap": "Mid", "sector": "Pharma", "predicted_return": 0.18, "volatility": "High", "price": 400},
        {"name": "Mphasis", "ticker": "MPHASIS.NS", "market_cap": "Large", "sector": "IT", "predicted_return": 0.15, "volatility": "Medium", "price": 2400},
        {"name": "Muthoot Finance", "ticker": "MUTHOOTFIN.NS", "market_cap": "Large", "sector": "Financials", "predicted_return": 0.14, "volatility": "Low", "price": 1700}, # Increased return
        {"name": "Navin Fluorine International", "ticker": "NAVINFLUOR.NS", "market_cap": "Mid", "sector": "Chemicals", "predicted_return": 0.17, "volatility": "Medium", "price": 3200},
        {"name": "Persistent Systems", "ticker": "PERSISTENT.NS", "market_cap": "Large", "sector": "IT", "predicted_return": 0.16, "volatility": "Medium", "price": 7800},
        {"name": "PVR Inox", "ticker": "PVRINOX.NS", "market_cap": "Mid", "sector": "Media & Entertainment", "predicted_return": 0.14, "volatility": "High", "price": 1400},
        {"name": "PI Industries", "ticker": "PIIND.NS", "market_cap": "Large", "sector": "Chemicals", "predicted_return": 0.13, "volatility": "Low", "price": 3800},
        {"name": "Polycab India", "ticker": "POLYCAB.NS", "market_cap": "Large", "sector": "Electrical Equipment", "predicted_return": 0.17, "volatility": "Medium", "price": 5800},
        {"name": "RBL Bank", "ticker": "RBLBANK.NS", "market_cap": "Mid", "sector": "Financials", "predicted_return": 0.16, "volatility": "Medium", "price": 250}, # Increased return
        {"name": "Route Mobile", "ticker": "ROUTEMOBILE.NS", "market_cap": "Small", "sector": "Telecom Services", "predicted_return": 0.20, "volatility": "High", "price": 1400},
        {"name": "Solar Industries India", "ticker": "SOLARINDS.NS", "market_cap": "Mid", "sector": "Chemicals", "predicted_return": 0.19, "volatility": "High", "price": 6000},
        {"name": "Tata Elxsi", "ticker": "TATAELXSI.NS", "market_cap": "Mid", "sector": "IT Services", "predicted_return": 0.18, "volatility": "High", "price": 7500},
        {"name": "Tata Communications", "ticker": "TATACOMM.NS", "market_cap": "Large", "sector": "Telecom Services", "predicted_return": 0.13, "volatility": "Low", "price": 1900},
        {"name": "Trent", "ticker": "TRENT.NS", "market_cap": "Large", "sector": "Retail", "predicted_return": 0.17, "volatility": "Medium", "price": 4500},
        {"name": "United Breweries", "ticker": "UBL.NS", "market_cap": "Large", "sector": "Beverages", "predicted_return": 0.10, "volatility": "Low", "price": 1900},
        {"name": "Voltas", "ticker": "VOLTAS.NS", "market_cap": "Large", "sector": "Consumer Durables", "predicted_return": 0.12, "volatility": "Medium", "price": 1400},
        {"name": "Astral", "ticker": "ASTRAL.NS", "market_cap": "Mid", "sector": "Building Materials", "predicted_return": 0.16, "volatility": "Medium", "price": 2000},
        {"name": "Avenue Supermarts", "ticker": "DMART.NS", "market_cap": "Large", "sector": "Retail", "predicted_return": 0.14, "volatility": "Low", "price": 4500},
        {"name": "Blue Dart Express", "ticker": "BLUEDART.NS", "market_cap": "Mid", "sector": "Logistics", "predicted_return": 0.15, "volatility": "Medium", "price": 7000},
        {"name": "Canara Bank", "ticker": "CANBK.NS", "market_cap": "Large", "sector": "Financials", "predicted_return": 0.12, "volatility": "Low", "price": 120}, # Increased return
        {"name": "Container Corporation of India", "ticker": "CONCOR.NS", "market_cap": "Large", "sector": "Logistics", "predicted_return": 0.11, "volatility": "Low", "price": 900},
        {"name": "Coromandel International", "ticker": "COROMANDEL.NS", "market_cap": "Mid", "sector": "Chemicals", "predicted_return": 0.13, "volatility": "Medium", "price": 1000},
        {"name": "Crompton Greaves Consumer Electricals", "ticker": "CROMPTON.NS", "market_cap": "Mid", "sector": "Consumer Durables", "predicted_return": 0.12, "volatility": "Low", "price": 300},
        {"name": "Devyani International", "ticker": "DEVYANI.NS", "market_cap": "Small", "sector": "Restaurants", "predicted_return": 0.20, "volatility": "High", "price": 180},
        {"name": "Federal Bank", "ticker": "FEDERALBNK.NS", "market_cap": "Mid", "sector": "Financials", "predicted_return": 0.13, "volatility": "Low", "price": 150}, # Increased return
        {"name": "Gland Pharma", "ticker": "GLAND.NS", "market_cap": "Mid", "sector": "Pharma", "predicted_return": 0.14, "volatility": "High", "price": 1800},
        {"name": "Gujarat Gas", "ticker": "GUJGASLTD.NS", "market_cap": "Mid", "sector": "Gas Distribution", "predicted_return": 0.11, "volatility": "Medium", "price": 500},
        {"name": "Honeywell Automation India", "ticker": "HONAUT.NS", "market_cap": "Mid", "sector": "Industrial Automation", "predicted_return": 0.15, "volatility": "Medium", "price": 40000},
        {"name": "Indian Bank", "ticker": "INDIANB.NS", "market_cap": "Large", "sector": "Financials", "predicted_return": 0.11, "volatility": "Low", "price": 300}, # Increased return
        {"name": "Indian Hotels Company", "ticker": "INDHOTEL.NS", "market_cap": "Mid", "sector": "Hospitality", "predicted_return": 0.16, "volatility": "Medium", "price": 600},
        {"name": "Jindal Steel & Power", "ticker": "JINDALSTEL.NS", "market_cap": "Large", "sector": "Metals", "predicted_return": 0.13, "volatility": "High", "price": 900},
        {"name": "Jubilant Pharmova", "ticker": "JUBILANT.NS", "market_cap": "Mid", "sector": "Pharma", "predicted_return": 0.12, "volatility": "Medium", "price": 450},
        {"name": "Kansai Nerolac Paints", "ticker": "KANSAINER.NS", "market_cap": "Mid", "sector": "Chemicals", "predicted_return": 0.10, "volatility": "Low", "price": 350},
        {"name": "L&T Technology Services", "ticker": "LTTS.NS", "market_cap": "Large", "sector": "IT Services", "predicted_return": 0.17, "volatility": "Medium", "price": 5500},
        {"name": "M&M Financial Services", "ticker": "MMFSL.NS", "market_cap": "Mid", "sector": "Financials", "predicted_return": 0.14, "volatility": "Medium", "price": 300}, # Increased return
        {"name": "Max Healthcare Institute", "ticker": "MAXHEALTH.NS", "market_cap": "Mid", "sector": "Healthcare", "predicted_return": 0.15, "volatility": "Medium", "price": 800},
        {"name": "Motilal Oswal Financial Services", "ticker": "MOTILALOFS.NS", "market_cap": "Mid", "sector": "Financials", "predicted_return": 0.21, "volatility": "Medium", "price": 2000}, # Increased return
        {"name": "NALCO", "ticker": "NATIONALUM.NS", "market_cap": "Mid", "sector": "Metals", "predicted_return": 0.10, "volatility": "Medium", "price": 180},
        {"name": "NMDC", "ticker": "NMDC.NS", "market_cap": "Large", "sector": "Mining", "predicted_return": 0.08, "volatility": "Low", "price": 250},
        {"name": "Oracle Financial Services Software", "ticker": "OFSS.NS", "market_cap": "Large", "sector": "IT", "predicted_return": 0.12, "volatility": "Low", "price": 9000},
        {"name": "Page Industries", "ticker": "PAGEIND.NS", "market_cap": "Large", "sector": "Apparel", "predicted_return": 0.15, "volatility": "Medium", "price": 38000},
        {"name": "Petronet LNG", "ticker": "PETRONET.NS", "market_cap": "Large", "sector": "Oil & Gas", "predicted_return": 0.09, "volatility": "Low", "price": 300},
        {"name": "Punjab National Bank", "ticker": "PNB.NS", "market_cap": "Large", "sector": "Financials", "predicted_return": 0.10, "volatility": "Low", "price": 100}, # Increased return
        {"name": "Zydus Lifesciences", "ticker": "ZYDUSLIFE.NS", "market_cap": "Large", "sector": "Pharma", "predicted_return": 0.11, "volatility": "Low", "price": 900}
    ],
    "mutual_funds": [ 
        {"name": "Parag Parikh Flexi Cap Fund", "type": "Equity", "category": "Flexi Cap", "predicted_return": 0.18, "volatility": "Medium", "amc": "PPFAS", "price": 60}, # NAV
        {"name": "ICICI Prudential Bluechip Fund", "type": "Equity", "category": "Large Cap", "predicted_return": 0.15, "volatility": "Low", "amc": "ICICI Pru", "price": 90},
        {"name": "Axis Midcap Fund", "type": "Equity", "category": "Mid Cap", "predicted_return": 0.20, "volatility": "Medium", "amc": "Axis", "price": 70},
        {"name": "SBI Small Cap Fund", "type": "Equity", "category": "Small Cap", "predicted_return": 0.22, "volatility": "High", "amc": "SBI", "price": 150},
        {"name": "Mirae Asset Emerging Bluechip Fund", "type": "Equity", "category": "Large & Mid Cap", "predicted_return": 0.19, "volatility": "Medium", "amc": "Mirae", "price": 100},
        {"name": "HDFC Liquid Fund", "type": "Debt", "category": "Liquid", "predicted_return": 0.06, "volatility": "Very Low", "amc": "HDFC", "price": 5000},
        {"name": "Aditya Birla Sun Life Frontline Equity Fund", "type": "Equity", "category": "Large Cap", "predicted_return": 0.14, "volatility": "Low", "amc": "Aditya Birla", "price": 400},
        {"name": "Nippon India Pharma Fund", "type": "Equity", "category": "Sectoral", "sector": "Healthcare", "predicted_return": 0.17, "volatility": "Medium", "amc": "Nippon", "price": 200},
        {"name": "ICICI Prudential Technology Fund", "type": "Equity", "category": "Sectoral", "sector": "IT", "predicted_return": 0.21, "volatility": "High", "amc": "ICICI Pru", "price": 180},
        {"name": "DSP Midcap Fund", "type": "Equity", "category": "Mid Cap", "predicted_return": 0.195, "volatility": "Medium", "amc": "DSP", "price": 120},
        {"name": "Quant Small Cap Fund", "type": "Equity", "category": "Small Cap", "predicted_return": 0.23, "volatility": "High", "amc": "Quant", "price": 130},
        # From image_7a0d25.png (Mutual Funds)
        {"name": "Aditya Birla Sun Life Frontline Equity Fund", "type": "Equity", "category": "Large Cap", "predicted_return": 0.14, "volatility": "Low", "amc": "Aditya Birla", "price": 400},
        {"name": "Axis Bluechip Fund", "type": "Equity", "category": "Large Cap", "predicted_return": 0.15, "volatility": "Low", "amc": "Axis", "price": 50},
        {"name": "Axis Growth Opportunities Fund", "type": "Equity", "category": "Large & Mid Cap", "predicted_return": 0.17, "volatility": "Medium", "amc": "Axis", "price": 25},
        {"name": "Axis Midcap Fund", "type": "Equity", "category": "Mid Cap", "predicted_return": 0.20, "volatility": "Medium", "amc": "Axis", "price": 70},
        {"name": "Axis Small Cap Fund", "type": "Equity", "category": "Small Cap", "predicted_return": 0.22, "volatility": "High", "amc": "Axis", "price": 80},
        {"name": "Canara Robeco Bluechip Equity Fund", "type": "Equity", "category": "Large Cap", "predicted_return": 0.145, "volatility": "Low", "amc": "Canara Robeco", "price": 45},
        {"name": "Canara Robeco Emerging Equities Fund", "type": "Equity", "category": "Large & Mid Cap", "predicted_return": 0.18, "volatility": "Medium", "amc": "Canara Robeco", "price": 120},
        {"name": "Edelweiss Large Cap Fund", "type": "Equity", "category": "Large Cap", "predicted_return": 0.13, "volatility": "Low", "amc": "Edelweiss", "price": 30},
        {"name": "Franklin India Feeder - US Opportunities Fund", "type": "Equity", "category": "International", "predicted_return": 0.19, "volatility": "High", "amc": "Franklin Templeton", "price": 50},
        {"name": "HDFC Balanced Advantage Fund", "type": "Hybrid", "category": "Balanced Advantage", "predicted_return": 0.16, "volatility": "Medium", "amc": "HDFC", "price": 400},
        {"name": "HDFC Flexi Cap Fund", "type": "Equity", "category": "Flexi Cap", "predicted_return": 0.17, "volatility": "Medium", "amc": "HDFC", "price": 70},
        {"name": "HDFC Large and Mid Cap Fund", "type": "Equity", "category": "Large & Mid Cap", "predicted_return": 0.165, "volatility": "Medium", "amc": "HDFC", "price": 100},
        {"name": "HDFC Mid-Cap Opportunities Fund", "type": "Equity", "category": "Mid Cap", "predicted_return": 0.21, "volatility": "Medium", "amc": "HDFC", "price": 150},
        {"name": "HDFC Small Cap Fund", "type": "Equity", "category": "Small Cap", "predicted_return": 0.23, "volatility": "High", "amc": "HDFC", "price": 100},
        {"name": "ICICI Prudential Equity & Debt Fund", "type": "Hybrid", "category": "Aggressive Hybrid", "predicted_return": 0.16, "volatility": "Medium", "amc": "ICICI Pru", "price": 300},
        {"name": "ICICI Prudential Flexicap Fund", "type": "Equity", "category": "Flexi Cap", "predicted_return": 0.17, "volatility": "Medium", "amc": "ICICI Pru", "price": 20},
        {"name": "ICICI Prudential Value Discovery Fund", "type": "Equity", "category": "Value", "predicted_return": 0.16, "volatility": "Medium", "amc": "ICICI Pru", "price": 280},
        {"name": "Kotak Emerging Equity Fund", "type": "Equity", "category": "Mid Cap", "predicted_return": 0.20, "volatility": "Medium", "amc": "Kotak", "price": 90},
        {"name": "Kotak Flexicap Fund", "type": "Equity", "category": "Flexi Cap", "predicted_return": 0.18, "volatility": "Medium", "amc": "Kotak", "price": 75},
        {"name": "L&T Midcap Fund", "type": "Equity", "category": "Mid Cap", "predicted_return": 0.19, "volatility": "Medium", "amc": "L&T", "price": 60},
        {"name": "Mirae Asset Emerging Bluechip Fund", "type": "Equity", "category": "Large & Mid Cap", "predicted_return": 0.19, "volatility": "Medium", "amc": "Mirae Asset", "price": 100},
        {"name": "Mirae Asset Large Cap Fund", "type": "Equity", "category": "Large Cap", "predicted_return": 0.15, "volatility": "Low", "amc": "Mirae Asset", "price": 80},
        {"name": "Mirae Asset Midcap Fund", "type": "Equity", "category": "Mid Cap", "predicted_return": 0.21, "volatility": "Medium", "amc": "Mirae Asset", "price": 70},
        {"name": "Mirae Asset Tax Saver Fund", "type": "Equity", "category": "ELSS", "predicted_return": 0.17, "volatility": "Medium", "amc": "Mirae Asset", "price": 30},
        {"name": "Nippon India Growth Fund", "type": "Equity", "category": "Mid Cap", "predicted_return": 0.20, "volatility": "Medium", "amc": "Nippon India", "price": 350},
        {"name": "PGIM India Flexi Cap Fund", "type": "Equity", "category": "Flexi Cap", "predicted_return": 0.175, "volatility": "Medium", "amc": "PGIM India", "price": 25},
        {"name": "Quant Active Fund", "type": "Equity", "category": "Flexi Cap", "predicted_return": 0.22, "volatility": "High", "amc": "Quant", "price": 500},
        {"name": "Quant Small Cap Fund", "type": "Equity", "category": "Small Cap", "predicted_return": 0.23, "volatility": "High", "amc": "Quant", "price": 130},
        {"name": "SBI Bluechip Fund", "type": "Equity", "category": "Large Cap", "predicted_return": 0.14, "volatility": "Low", "amc": "SBI", "price": 60},
        {"name": "SBI Contra Fund", "type": "Equity", "category": "Contra", "predicted_return": 0.19, "volatility": "Medium", "amc": "SBI", "price": 280},
        {"name": "SBI Equity Hybrid Fund", "type": "Hybrid", "category": "Aggressive Hybrid", "predicted_return": 0.15, "volatility": "Medium", "amc": "SBI", "price": 250},
        {"name": "SBI Flexicap Fund", "type": "Equity", "category": "Flexi Cap", "predicted_return": 0.17, "volatility": "Medium", "amc": "SBI", "price": 30},
        {"name": "SBI Large & Midcap Fund", "type": "Equity", "category": "Large & Mid Cap", "predicted_return": 0.16, "volatility": "Medium", "amc": "SBI", "price": 400},
        {"name": "SBI Long Term Equity Fund", "type": "Equity", "category": "ELSS", "predicted_return": 0.16, "volatility": "Medium", "amc": "SBI", "price": 350},
        {"name": "Sundaram Mid Cap Fund", "type": "Equity", "category": "Mid Cap", "predicted_return": 0.18, "volatility": "Medium", "amc": "Sundaram", "price": 100},
        {"name": "Tata Digital India Fund", "type": "Equity", "category": "Sectoral", "sector": "IT", "predicted_return": 0.20, "volatility": "High", "amc": "Tata", "price": 40},
        {"name": "Tata Ethical Fund", "type": "Equity", "category": "Thematic", "predicted_return": 0.15, "volatility": "Medium", "amc": "Tata", "price": 30},
        {"name": "Tata Flexi Cap Fund", "type": "Equity", "category": "Flexi Cap", "predicted_return": 0.16, "volatility": "Medium", "amc": "Tata", "price": 25},
        {"name": "Tata Large & Mid Cap Fund", "type": "Equity", "category": "Large & Mid Cap", "predicted_return": 0.155, "volatility": "Medium", "amc": "Tata", "price": 200},
        {"name": "UTI Flexi Cap Fund", "type": "Equity", "category": "Flexi Cap", "predicted_return": 0.17, "volatility": "Medium", "amc": "UTI", "price": 300},
        {"name": "UTI Mid Cap Fund", "type": "Equity", "category": "Mid Cap", "predicted_return": 0.19, "volatility": "Medium", "amc": "UTI", "price": 250},
        {"name": "WhiteOak Capital Flexi Cap Fund", "type": "Equity", "category": "Flexi Cap", "predicted_return": 0.19, "volatility": "Medium", "amc": "WhiteOak Capital", "price": 15},
        {"name": "UTI Nifty 50 Index Fund", "type": "Equity", "category": "Large Cap Index Fund", "predicted_return": 0.137, "volatility": "Low", "amc": "UTI", "price": 140},
        {"name": "Motilal Oswal S&P 500 Index Fund", "type": "Equity", "category": "International Index Fund", "predicted_return": 0.17, "volatility": "Medium", "amc": "Motilal Oswal", "price": 30},
        {"name": "SBI Debt Hybrid Fund", "type": "Hybrid", "category": "Conservative Hybrid", "predicted_return": 0.08, "volatility": "Low", "amc": "SBI", "price": 100},
        {"name": "Aditya Birla Sun Life Liquid Fund", "type": "Debt", "category": "Liquid", "predicted_return": 0.061, "volatility": "Very Low", "amc": "Aditya Birla", "price": 4000},
        {"name": "Axis Liquid Fund", "type": "Debt", "category": "Liquid", "predicted_return": 0.06, "volatility": "Very Low", "amc": "Axis", "price": 1000},
        {"name": "ICICI Prudential Liquid Fund", "type": "Debt", "category": "Liquid", "predicted_return": 0.062, "volatility": "Very Low", "amc": "ICICI Pru", "price": 3000},
        {"name": "Kotak Liquid Fund", "type": "Debt", "category": "Liquid", "predicted_return": 0.06, "volatility": "Very Low", "amc": "Kotak", "price": 2000},
        {"name": "Mirae Asset Liquid Fund", "type": "Debt", "category": "Liquid", "predicted_return": 0.061, "volatility": "Very Low", "amc": "Mirae Asset", "price": 1000},
        {"name": "Nippon India Liquid Fund", "type": "Debt", "category": "Liquid", "predicted_return": 0.06, "volatility": "Very Low", "amc": "Nippon India", "price": 5000},
        {"name": "SBI Liquid Fund", "type": "Debt", "category": "Liquid", "predicted_return": 0.062, "volatility": "Very Low", "amc": "SBI", "price": 4500},
        {"name": "Tata Liquid Fund", "type": "Debt", "category": "Liquid", "predicted_return": 0.06, "volatility": "Very Low", "amc": "Tata", "price": 1500},
        {"name": "UTI Liquid Fund", "type": "Debt", "category": "Liquid", "predicted_return": 0.061, "volatility": "Very Low", "amc": "UTI", "price": 2500},
        {"name": "Aditya Birla Sun Life Corporate Bond Fund", "type": "Debt", "category": "Corporate Bond", "predicted_return": 0.07, "volatility": "Low", "amc": "Aditya Birla", "price": 50},
        {"name": "Axis Corporate Bond Fund", "type": "Debt", "category": "Corporate Bond", "predicted_return": 0.072, "volatility": "Low", "amc": "Axis", "price": 40},
        {"name": "HDFC Corporate Bond Fund", "type": "Debt", "category": "Corporate Bond", "predicted_return": 0.07, "price": 105},
        {"name": "ICICI Prudential Corporate Bond Fund", "type": "Debt", "category": "Corporate Bond", "predicted_return": 0.071, "price": 60},
        {"name": "Kotak Corporate Bond Fund", "type": "Debt", "category": "Corporate Bond", "predicted_return": 0.07, "price": 55},
        {"name": "Nippon India Corporate Bond Fund", "type": "Debt", "category": "Corporate Bond", "predicted_return": 0.072, "price": 70},
        {"name": "SBI Corporate Bond Fund", "type": "Debt", "category": "Corporate Bond", "predicted_return": 0.071, "price": 80},
        {"name": "UTI Corporate Bond Fund", "type": "Debt", "category": "Corporate Bond", "predicted_return": 0.07, "price": 90},
        {"name": "Aditya Birla Sun Life Government Securities Fund", "type": "Debt", "category": "Gilt", "predicted_return": 0.075, "price": 30},
        {"name": "ICICI Prudential Gilt Fund", "type": "Debt", "category": "Gilt Fund", "predicted_return": 0.075, "price": 120},
        {"name": "SBI Gilt Fund", "type": "Debt", "category": "Gilt", "predicted_return": 0.076, "price": 110},
        {"name": "HDFC Credit Risk Debt Fund", "type": "Debt", "category": "Credit Risk", "predicted_return": 0.08, "price": 30},
        {"name": "SBI Banking & PSU Fund", "type": "Debt", "category": "Banking & PSU", "predicted_return": 0.073, "price": 25}
    ],
    "equity_etfs_index_funds": [
        {"name": "Nippon India ETF Nifty 50 BeES", "ticker": "NIFTYBEES", "type": "Equity", "category": "Large Cap Index ETF", "predicted_return": 0.14, "price": 260},
        {"name": "SBI Nifty 50 ETF", "ticker": "SETFNIF50", "type": "Equity", "category": "Large Cap Index ETF", "predicted_return": 0.138, "price": 250},
        {"name": "UTI Nifty 50 Index Fund", "type": "Equity", "category": "Large Cap Index Fund", "predicted_return": 0.137, "price": 140},
        {"name": "Nippon India ETF Nifty Next 50 Junior BeES", "ticker": "JUNIORBEES", "type": "Equity", "category": "Mid Cap Index ETF", "predicted_return": 0.16, "price": 600},
        {"name": "Axis Nifty 100 Index Fund", "type": "Equity", "category": "Large Cap Index Fund", "predicted_return": 0.135, "price": 130},
        {"name": "Motilal Oswal NASDAQ 100 ETF", "ticker": "MON100", "type": "Equity", "category": "International Index ETF", "predicted_return": 0.17, "price": 1500},
    ],
    "debt_etfs_index_funds": [
        {"name": "ICICI Prudential Gilt Fund", "type": "Debt", "category": "Gilt Fund", "predicted_return": 0.075, "price": 120}, # NAV
        {"name": "SBI Long Duration Fund", "type": "Debt", "category": "Long Duration", "predicted_return": 0.08, "price": 110},
        {"name": "HDFC Corporate Bond Fund", "type": "Debt", "category": "Corporate Bond", "predicted_return": 0.07, "price": 105},
        {"name": "Nippon India Nifty Target Maturity Fund - 2030", "type": "Debt", "category": "Target Maturity", "predicted_return": 0.078, "price": 100},
        {"name": "BHARAT Bond ETF - April 2032", "ticker": "BBETF0432", "type": "Debt", "category": "Target Maturity ETF", "predicted_return": 0.077, "price": 1000},
        {"name": "SBI-ETF 10Y Gilt", "ticker": "SBILTGILT", "type": "Debt", "category": "Gilt ETF", "predicted_return": 0.076, "price": 100},
    ],
    "gold_etfs": [
        {"name": "Nippon India ETF Gold BeES", "ticker": "GOLDBEES", "predicted_return": 0.09, "price": 60},
        {"name": "SBI Gold ETF", "ticker": "SETFGOLD", "predicted_return": 0.088, "price": 58},
        {"name": "ICICI Prudential Gold ETF", "ticker": "GOLDIETF", "predicted_return": 0.089, "price": 59},
    ]
}